spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fallboot
    username: myUser
    password: password1234
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: pixel-updates
    consumer:
      group-id: fallboot-kafka-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.andy.fallboot.shared.*
