services:
  postgres:
    image: postgres:17
    container_name: fallboot-postgres-dev
    environment:
      POSTGRES_DB: fallboot
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: password1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
  rabbitmq:
    image: rabbitmq:4-management
    container_name: fallboot-rabbitmq-dev
    environment:
      RABBITMQ_ENABLED_PLUGINS: "rabbitmq_stomp,rabbitmq_management"
    ports:
      - "15672:15672"
      - "61613:61613"
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_stomp rabbitmq_management && rabbitmq-server"
volumes:
  postgres_data:

  redis-data:
    driver: local # Defines the local volume