spring:
  application:
    name: fallboot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
fallboot:
  cdn:
    base-url: ${FALLBOOT_CDN_BASE_URL:http://localhost:9000/fallboot-snapshots}
management:
  endpoints:
    web:
      exposure:
        include: health,threaddump,metrics
